// Computer Hardware Quiz — question bank
// Each question: category, difficulty (easy|medium|hard), question, answers[], correct (index), explain (shown after answering)

var QUESTIONS = [
  // ===== CPUs =====
  { category: "CPU", difficulty: "easy", question: "What does CPU stand for?", answers: ["Central Processing Unit", "Computer Personal Unit", "Central Program Utility", "Core Processing Underlay"], correct: 0, explain: "The CPU is the computer's main general-purpose processor — it executes the instructions of every program you run." },
  { category: "CPU", difficulty: "easy", question: "Which company makes Ryzen processors?", answers: ["Intel", "AMD", "NVIDIA", "Qualcomm"], correct: 1, explain: "Ryzen is AMD's desktop and laptop CPU family, launched in 2017 to compete directly with Intel's Core lineup." },
  { category: "CPU", difficulty: "easy", question: "What component keeps a CPU cool?", answers: ["Heat sink / cooler", "Sound card", "Power strip", "Network card"], correct: 0, explain: "A heat sink (with a fan, or a liquid cooler) draws heat away from the CPU die; thermal paste improves the contact between them." },
  { category: "CPU", difficulty: "medium", question: "What does 'overclocking' a CPU mean?", answers: ["Increasing its clock speed beyond factory settings", "Installing more RAM", "Replacing the thermal paste", "Running it at lower voltage"], correct: 0, explain: "Overclocking pushes the chip above its rated GHz for extra performance — at the cost of more heat and power draw." },
  { category: "CPU", difficulty: "medium", question: "What is a 'core' in a CPU?", answers: ["An independent processing unit that can execute instructions", "The cache memory of the chip", "A connector on the motherboard", "A type of cooling system"], correct: 0, explain: "Each core is a full processor capable of running tasks independently — more cores means better multitasking and parallel workloads." },
  { category: "CPU", difficulty: "hard", question: "Which Intel socket is compatible with 12th-gen Core desktop CPUs?", answers: ["LGA 1700", "AM4", "LGA 1200", "TRX40"], correct: 0, explain: "Alder Lake (12th gen) uses Intel's LGA 1700 socket; AM4 is AMD's, and LGA 1200 belongs to 10th/11th gen." },
  { category: "CPU", difficulty: "hard", question: "What is SMT (Simultaneous Multi-Threading) used for?", answers: ["Allowing each physical core to run multiple threads at once", "Cooling the processor more efficiently", "Encrypting data in the cache", "Boosting GPU performance"], correct: 0, explain: "SMT (Intel calls it Hyper-Threading) lets one physical core juggle two threads, improving throughput by keeping execution units busy." },
  { category: "CPU", difficulty: "hard", question: "What is the main role of CPU cache (L1/L2/L3)?", answers: ["Store frequently accessed data close to the cores for fast access", "Permanently store the operating system", "Convert AC power to DC power", "Render graphics frames"], correct: 0, explain: "Cache is tiny but extremely fast memory on the chip itself; L1 is fastest and closest to each core, L3 is larger and shared." },

  // ===== RAM =====
  { category: "RAM", difficulty: "easy", question: "What does RAM stand for?", answers: ["Random Access Memory", "Rapid Action Module", "Read And Memorize", "Runtime Access Manager"], correct: 0, explain: "'Random access' means any memory location can be reached directly in the same amount of time — no sequential searching." },
  { category: "RAM", difficulty: "easy", question: "What happens to data in RAM when the PC loses power?", answers: ["It is lost because RAM is volatile", "It is saved permanently", "It moves to the hard drive automatically", "Nothing changes"], correct: 0, explain: "RAM needs constant power to hold data — that's why unsaved work disappears during an outage or forced shutdown." },
  { category: "RAM", difficulty: "easy", question: "Which of these has MORE capacity?", answers: ["16 GB", "8 GB", "4 GB", "2 GB"], correct: 0, explain: "Capacity is measured in bytes: 16 GB holds twice as much as 8 GB. More RAM lets you keep more apps open at once." },
  { category: "RAM", difficulty: "medium", question: "What does dual-channel memory do?", answers: ["Increases memory bandwidth by using two sticks in parallel", "Doubles the RAM capacity", "Cools the RAM modules", "Makes RAM non-volatile"], correct: 0, explain: "With two matched sticks, the memory controller reads/writes both simultaneously — same capacity, up to double the bandwidth." },
  { category: "RAM", difficulty: "medium", question: "Which RAM generation is newer?", answers: ["DDR5", "DDR3", "DDR2", "DDR"], correct: 0, explain: "DDR5 arrived in 2021 with higher speeds and capacity per stick than DDR4, which itself doubled DDR3's potential rate." },
  { category: "RAM", difficulty: "hard", question: "What does CAS latency (CL) measure in RAM?", answers: ["The delay between a command and when data is available", "The maximum storage size", "The operating temperature", "The number of channels"], correct: 0, explain: "CL counts clock cycles the memory waits before delivering requested data — lower is faster, though absolute time also depends on clock speed." },
  { category: "RAM", difficulty: "hard", question: "Which feature detects and corrects memory errors, common in servers?", answers: ["ECC", "RGB", "XMP", "SLI"], correct: 0, explain: "ECC (Error-Correcting Code) memory fixes single-bit errors on the fly — essential for servers where a random flip could corrupt data." },

  // ===== Storage =====
  { category: "Storage", difficulty: "easy", question: "Which type of drive has NO moving parts?", answers: ["SSD", "HDD", "Floppy disk", "Tape drive"], correct: 0, explain: "SSDs store bits in flash memory chips accessed electrically — no spinning platters or moving arms to break." },
  { category: "Storage", difficulty: "easy", question: "Which usually offers FASTER load times?", answers: ["NVMe SSD", "5400 RPM HDD", "DVD drive", "USB 2.0 flash drive"], correct: 0, explain: "An NVMe SSD over PCIe can exceed 3,500 MB/s — dozens of times faster than any spinning hard drive." },
  { category: "Storage", difficulty: "easy", question: "What unit measures storage capacity?", answers: ["Gigabyte (GB)", "Megahertz (MHz)", "Volt (V)", "Watt (W)"], correct: 0, explain: "GB measures how many billions of bytes fit; MHz measures frequency, volts measure electrical potential, watts measure power." },
  { category: "Storage", difficulty: "medium", question: "What interface connects an M.2 NVMe SSD to modern motherboards?", answers: ["PCIe", "SATA power only", "IDE", "FireWire"], correct: 0, explain: "M.2 is just the connector shape — NVMe drives use PCIe lanes (usually x4) for their high bandwidth." },
  { category: "Storage", difficulty: "medium", question: "What is the approximate max speed of SATA III?", answers: ["6 Gb/s", "60 Gb/s", "600 Mb/s", "32 Gb/s"], correct: 0, explain: "SATA III tops out at 6 gigabits per second (~550 MB/s real world) — which is why fast NVMe drives leave it behind." },
  { category: "Storage", difficulty: "hard", question: "What is the main advantage of NVMe over SATA SSDs?", answers: ["It uses PCIe lanes for much higher bandwidth and lower latency", "It stores data magnetically", "It requires no power", "It works without a motherboard"], correct: 0, explain: "The NVMe protocol speaks directly to the CPU over PCIe, removing the old SATA controller bottleneck entirely." },
  { category: "Storage", difficulty: "hard", question: "Why should HDDs be defragmented but SSDs generally not?", answers: ["SSDs access all cells equally fast, so fragmentation doesn't slow them and defrag causes extra wear", "Defragmenting erases SSD firmware", "HDDs cannot store fragmented files", "SSDs are always smaller than 1 TB"], correct: 0, explain: "Seeking takes time on HDDs, so grouping related sectors helps. On SSDs every cell responds equally fast — defragging only burns write cycles." },

  // ===== GPUs =====
  { category: "GPU", difficulty: "easy", question: "What does GPU stand for?", answers: ["Graphics Processing Unit", "General Power Unit", "Gaming Processor Utility", "Graphic Port Universal"], correct: 0, explain: "The GPU is a parallel processor with thousands of small cores, originally built to calculate pixels for displays." },
  { category: "GPU", difficulty: "easy", question: "Which companies make the main dedicated gaming GPUs?", answers: ["NVIDIA and AMD", "Apple and Dell", "Seagate and WD", "Logitech and Razer"], correct: 0, explain: "NVIDIA (GeForce) and AMD (Radeon) dominate discrete graphics; Intel's Arc is the newer third contender." },
  { category: "GPU", difficulty: "easy", question: "Where does a dedicated graphics card get installed?", answers: ["In a PCIe expansion slot on the motherboard", "Inside the power supply", "On top of the CPU", "In a RAM slot"], correct: 0, explain: "Gaming cards use a physical x16 PCIe slot below the CPU, plus extra power from the PSU via PCIe cables." },
  { category: "GPU", difficulty: "medium", question: "What technology renders multiple frames at once to smooth gameplay?", answers: ["Frame rate (FPS)", "Pixel shader", "Anti-aliasing only", "Thermal throttling"], correct: 0, explain: "Frames per second measures how many complete images the GPU outputs each second — higher FPS looks smoother." },
  { category: "GPU", difficulty: "medium", question: "What does NVIDIA's DLSS do?", answers: ["Uses AI to upscale lower-resolution images for better performance", "Overclocks the CPU automatically", "Adds more VRAM to the card", "Compresses game downloads"], correct: 0, explain: "DLSS renders the game at lower resolution, then an AI model reconstructs it near-native quality — big FPS gains. AMD's rival is FSR." },
  { category: "GPU", difficulty: "hard", question: "What does VRAM do in a graphics card?", answers: ["Stores textures, frame buffers and assets for fast GPU access", "Cools the GPU die", "Controls monitor brightness", "Stores BIOS settings"], correct: 0, explain: "VRAM is dedicated memory right next to the GPU; when games exceed it, they fall back to slow system RAM and stutter." },
  { category: "GPU", difficulty: "hard", question: "What happens during GPU 'thermal throttling'?", answers: ["The GPU reduces its clocks to lower temperature", "The GPU increases fan noise permanently", "The GPU disables VRAM completely", "The monitor refresh rate doubles"], correct: 0, explain: "When the chip hits its temperature limit, it deliberately slows down to protect itself — that's why cooling matters for sustained performance." },

  // ===== Motherboards & Power =====
  { category: "Motherboard & Power", difficulty: "easy", question: "Where do you plug in the CPU on a PC?", answers: ["The motherboard's CPU socket", "The power supply", "A USB port", "The graphics card"], correct: 0, explain: "The socket (LGA on modern Intel/AMD boards) holds the processor; a lever locks it and cooler mounts on top." },
  { category: "Motherboard & Power", difficulty: "easy", question: "What does PSU stand for?", answers: ["Power Supply Unit", "Personal System Utility", "Primary Storage Unit", "Processor Speed Unifier"], correct: 0, explain: "The PSU converts wall AC into the regulated DC voltages (+12 V, +5 V, +3.3 V) every component needs." },
  { category: "Motherboard & Power", difficulty: "easy", question: "What is BIOS/UEFI used for?", answers: ["Firmware that initializes hardware before the OS boots", "Editing photos", "Browsing the web", "Measuring room temperature"], correct: 0, explain: "UEFI (the modern BIOS) wakes the hardware, checks it (POST), then hands off boot to your drive's operating system." },
  { category: "Motherboard & Power", difficulty: "medium", question: "What does a motherboard chipset do?", answers: ["Manages communication between CPU, memory and peripherals", "Cools the entire case", "Displays images on screen", "Provides Wi-Fi only"], correct: 0, explain: "Modern chipsets are the traffic controllers for USB, SATA, M.2 lanes and expansion slots around the CPU." },
  { category: "Motherboard & Power", difficulty: "medium", question: "Which PSU rating indicates high efficiency?", answers: ["80 Plus Gold", "80 Plus Red", "Tier Blue", "Class Z"], correct: 0, explain: "80 Plus tiers run Standard → Bronze → Silver → Gold → Platinum → Titanium; Gold converts ~90% at typical load." },
  { category: "Motherboard & Power", difficulty: "hard", question: "What is the purpose of the CMOS battery on a motherboard?", answers: ["Keeps RTC clock and BIOS settings alive when powered off", "Powers the GPU during gaming", "Charges USB devices", "Boosts CPU overclocks"], correct: 0, explain: "That coin cell (usually CR2032) keeps the real-time clock ticking and preserves UEFI settings when the PC is unplugged." },
  { category: "Motherboard & Power", difficulty: "hard", question: "What connector typically powers a modern dedicated GPU?", answers: ["6/8-pin PCIe power connector", "Molex 4-pin only", "SATA cable", "Ethernet port"], correct: 0, explain: "PCIe 6- and 8-pin connectors deliver the extra 75–300 W cards need beyond what the slot supplies (newer cards use 16-pin 12VHPWR)." },
  { category: "Motherboard & Power", difficulty: "hard", question: "ATX 3.0 PSUs introduced which new native GPU power connector?", answers: ["12VHPWR (16-pin)", "24-pin EPS", "Molex Micro-Fit", "USB-C PD only"], correct: 0, explain: "ATX 3.0 added the 16-pin 12VHPWR (up to 600 W) designed for high-end GPUs like NVIDIA's RTX 40 series." },

  // ===== Peripherals =====
  { category: "Peripherals", difficulty: "easy", question: "Which of these is an INPUT device?", answers: ["Keyboard", "Monitor", "Printer", "Speaker"], correct: 0, explain: "Input devices send data INTO the computer (keyboard, mouse, mic); monitors, printers and speakers output it." },
  { category: "Peripherals", difficulty: "easy", question: "Which cable commonly connects a PC to a modern monitor?", answers: ["HDMI or DisplayPort", "Ethernet", "Phone jack", "Coaxial"], correct: 0, explain: "Both carry digital video+audio; DisplayPort supports higher refresh rates, HDMI is the universal TV/console standard." },
  { category: "Peripherals", difficulty: "medium", question: "DisplayPort 1.4 supports roughly what maximum resolution at 60 Hz?", answers: ["8K (7680×4320)", "480p", "720p only", "It cannot carry video"], correct: 0, explain: "DP 1.4's 32.4 Gb/s bandwidth handles 8K@60Hz with DSC compression — or 4K@144Hz without breaking a sweat." },
  { category: "Peripherals", difficulty: "medium", question: "What does a USB hub do?", answers: ["Expands one USB port into multiple ports", "Speeds up the internet connection", "Cools down the mouse", "Converts HDMI to audio"], correct: 0, explain: "A hub splits one upstream port among several devices — they all share the original port's total bandwidth." },
  { category: "Peripherals", difficulty: "hard", question: "Which display technology allows individual pixels to turn off for perfect blacks?", answers: ["OLED", "TN LCD with CCFL", "CRT", "Plasma"], correct: 0, explain: "Every OLED pixel emits its own light, so 'black' pixels switch fully off — LCD backlights can never fully block their glow." },
  { category: "Peripherals", difficulty: "hard", question: "What advantage does a mechanical keyboard switch offer over a basic membrane dome?", answers: ["Distinct tactile feedback and per-key durability ratings", "Silent operation guaranteed", "Built-in speakers", "No need for a USB port"], correct: 0, explain: "Each key has its own spring switch rated for tens of millions of presses, with consistent feel — membrane domes degrade mushily over time." }
];
